In [3]:
myNum = [[2,8,17,21,46,47],[13,17,22,25,27,48],[3,6,9,13,14,30],[19,29,34,42,45,46],[3,12,14,21,33,40],[3,6,10,25,36,37],
          [1,4,13,22,24,45],[3,6,10,24,25,44],[2,6,11,20,30,45],[4,15,16,28,34,40],[3,8,15,23,28,39],[9,13,22,34,33,40],
          [4,5,15,24,25,26],[11,18,20,21,28,30],[1,2,7,18,34,36],[1,2,7,32,40,47],[3,5,16,22,28,36],[5,8,12,13,60,43],
          [4,15,26,30,31,48],[6,10,30,35,41,46],]
priceNum = [[7,21,22,37,41,48,15],[4,41,24,7,27,23,17],[3,5,17,32,33,47,36]]
specialNum = [[1,4,7,17,18,24,26,35,38,42],[10,22,24,26,27,31,32,35,40,46],[7,8,9,11,12,16,25,29,41,47]]
def whatPrice(match) :
    if match == 2.5 :
        return "柒獎"
    elif match == 3 :
        return "普獎"
    elif match == 3.5 :
        return "陸獎"
    elif match == 4 :
        return "伍獎"
    elif match == 4.5 :
        return "肆獎"
    elif match == 5 :
        return "參獎"
    elif match == 5.5 :
        return "貳獎"
    elif match == 6 :
        return "頭獎"
    else :
        return "三小都沒"
for lengthOfPN in range(len(priceNum)) :
    matchlist = []
    for lengthOfMN in range(len(myNum)) :
        match = 0
        for num in priceNum[lengthOfPN] :
            if num in myNum[lengthOfMN] :
                if num != priceNum[lengthOfPN][len(priceNum[lengthOfPN])-1] :
                    match = match + 1
                else :
                    match = match + 0.5
        matchlist.append(match)
        if match >= 2.5 :
            print whatPrice(match)
for lengthOfSN in range(len(specialNum)) :
    matchlists = []
    for lengthOfMN in range(len(myNum)) :
        match = 0
        for num in specialNum[lengthOfSN] :
            if num in myNum[lengthOfMN] :
                match = match + 1
        matchlists.append(match)
        if match > 3 :
            print whatPrice(match)
print '一般最多對中 : ' + str(max(matchlist)) + '個' 
print '特別最多對中 : ' + str(max(matchlists)) +  '個' 

柒獎
一般最多對中 : 2.5個
特別最多對中 : 2個


In [14]:
from numpy import *
x = ones(9).reshape(3,3)
fill_diagonal(x,10)
x[2][1] = 100
print x
print x[1]
print x[2]

[[  10.    1.    1.]
 [   1.   10.    1.]
 [   1.  100.   10.]]
[  1.  10.   1.]
[   1.  100.   10.]


In [20]:
if not (False and False and False):
    print 'x'

x
